--CREATE TABLE IF NOT EXISTS "demo".employee (
--   id int NOT NULL PRIMARY KEY,
--   employee_salary int,
--   employee_name varchar(255)  not null,
--   employee_age int,
--   profile_image varchar(255),
--) ;